# CMake generated Testfile for 
# Source directory: /home/ashwini/Documents/driving_python/image_processing/cmake/Tests/RunCMake
# Build directory: /home/ashwini/Documents/driving_python/image_processing/cmake/Tests/RunCMake
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(RunCMake.ObjectLibrary "/home/ashwini/Documents/driving_python/image_processing/cmake/bin/cmake" "-DCMAKE_MODULE_PATH=/home/ashwini/Documents/driving_python/image_processing/cmake/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/ashwini/Documents/driving_python/image_processing/cmake/Tests/RunCMake/ObjectLibrary" "-DRunCMake_BINARY_DIR=/home/ashwini/Documents/driving_python/image_processing/cmake/Tests/RunCMake/ObjectLibrary" "-P" "/home/ashwini/Documents/driving_python/image_processing/cmake/Tests/RunCMake/ObjectLibrary/RunCMakeTest.cmake")
ADD_TEST(RunCMake.build_command "/home/ashwini/Documents/driving_python/image_processing/cmake/bin/cmake" "-DCMAKE_MODULE_PATH=/home/ashwini/Documents/driving_python/image_processing/cmake/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/ashwini/Documents/driving_python/image_processing/cmake/Tests/RunCMake/build_command" "-DRunCMake_BINARY_DIR=/home/ashwini/Documents/driving_python/image_processing/cmake/Tests/RunCMake/build_command" "-P" "/home/ashwini/Documents/driving_python/image_processing/cmake/Tests/RunCMake/build_command/RunCMakeTest.cmake")
ADD_TEST(RunCMake.find_package "/home/ashwini/Documents/driving_python/image_processing/cmake/bin/cmake" "-DCMAKE_MODULE_PATH=/home/ashwini/Documents/driving_python/image_processing/cmake/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/ashwini/Documents/driving_python/image_processing/cmake/Tests/RunCMake/find_package" "-DRunCMake_BINARY_DIR=/home/ashwini/Documents/driving_python/image_processing/cmake/Tests/RunCMake/find_package" "-P" "/home/ashwini/Documents/driving_python/image_processing/cmake/Tests/RunCMake/find_package/RunCMakeTest.cmake")
