/*
 * Generated by /home/ashwini/Documents/driving_python/image_processing/cmake/bootstrap
 * Version:     $Revision$
 *
 * Source directory: /home/ashwini/Documents/driving_python/image_processing/cmake
 * Binary directory: /home/ashwini/Documents/driving_python/image_processing/cmake/Bootstrap.cmk
 *
 * C compiler:   gcc
 * C flags:      
 *
 * C++ compiler: g++
 * C++ flags:    
 *
 * Make:         make
 *
 * Sources:
 *   cmStandardIncludes   cmake    cmakemain   cmakewizard    cmCommandArgumentLexer   cmCommandArgumentParser   cmCommandArgumentParserHelper   cmDefinitions   cmDepends   cmDependsC   cmDocumentationFormatter   cmDocumentationFormatterText   cmPolicies   cmProperty   cmPropertyMap   cmPropertyDefinition   cmPropertyDefinitionMap   cmMakeDepend   cmMakefile   cmExportFileGenerator   cmExportInstallFileGenerator   cmInstallDirectoryGenerator   cmGeneratedFileStream   cmGeneratorTarget   cmGeneratorExpression   cmGlobalGenerator   cmLocalGenerator   cmInstallGenerator   cmInstallExportGenerator   cmInstallFilesGenerator   cmInstallScriptGenerator   cmInstallTargetGenerator   cmScriptGenerator   cmSourceFile   cmSourceFileLocation   cmSystemTools   cmTestGenerator   cmVersion   cmFileTimeComparison   cmGlobalUnixMakefileGenerator3   cmLocalUnixMakefileGenerator3   cmMakefileExecutableTargetGenerator   cmMakefileLibraryTargetGenerator   cmMakefileTargetGenerator   cmMakefileUtilityTargetGenerator   cmNewLineStyle   cmBootstrapCommands   cmCommands   cmTarget   cmTest   cmCustomCommand   cmCustomCommandGenerator   cmDocumentVariables   cmCacheManager   cmListFileCache   cmComputeLinkDepends   cmComputeLinkInformation   cmOrderDirectories   cmComputeTargetDepends   cmComputeComponentGraph   cmExprLexer   cmExprParser   cmExprParserHelper    cmListFileLexer   
 * kwSys Sources:
 *   Directory   Glob   RegularExpression   SystemTools     ProcessUNIX     String     System 
 */

/* #undef CMAKE_NO_STD_NAMESPACE */
/* #undef CMAKE_NO_ANSI_STREAM_HEADERS */
/* #undef CMAKE_NO_ANSI_STRING_STREAM */
/* #undef CMAKE_NO_ANSI_FOR_SCOPE */
#define CMAKE_ROOT_DIR "/home/ashwini/Documents/driving_python/image_processing/cmake"
#define CMAKE_DATA_DIR "/share/cmake-2.8"
#define CMAKE_BOOTSTRAP
